import {initSubmission} from './submission.mjs';
import {CodexPreview} from './codex-preview.mjs';
import {t,language,setLanguage,translatePage} from './i18n.mjs';
const $=id=>document.getElementById(id);let items=[],selected=null,preview=null,privateUrl=null,timer,localApiAvailable=false;
function toast(text){$('galleryToast').textContent=t(text);$('galleryToast').hidden=false;clearTimeout(timer);timer=setTimeout(()=>$('galleryToast').hidden=true,4000);}
async function api(path,body){const r=await fetch('/api/'+path,body?{method:'POST',headers:{'Content-Type':'application/json','X-Bubble-Studio':'1'},body:JSON.stringify(body)}:undefined);const data=await r.json();if(!r.ok)throw Error(data.error);return data;}
function name(item){return language==='en'?(item.nameEn||item.name):item.name;}
function count(value){if(value==null)return t('暂未统计');return t('{count} 次下载',{count:value.toLocaleString(language==='en'?'en-US':'zh-CN')});}
function cards(){const container=$('cards');container.replaceChildren();for(const item of items){const button=document.createElement('button');button.className='preset-card';button.dataset.id=item.id;const art=document.createElement('div');art.className='preset-card-art';const img=new Image();img.src=item.url;img.alt=name(item);const label=document.createElement('span');label.className='preset-label';label.textContent=item.community?(language==='en'?'Community':'社区作品'):t('内置预设');art.append(img,label);const info=document.createElement('div');info.className='preset-card-info';const title=document.createElement('h2');title.textContent=name(item);const description=document.createElement('p');description.textContent=item.description[language];const meta=document.createElement('div');meta.className='preset-card-meta';const author=document.createElement('span');author.textContent=item.author;const downloads=document.createElement('span');downloads.className='count';downloads.textContent='↓ '+count(item.downloads);meta.append(author,downloads);info.append(title,description,meta);button.append(art,info);button.onclick=()=>open(item);container.append(button);}}
function detailText(){if(!selected)return;$('detailKind').textContent=selected.community?(language==='en'?'Community':'社区作品'):t(selected.private?'个人预览':'内置预设');$('detailName').textContent=name(selected);$('detailMeta').textContent=`${selected.width} × ${selected.height} px · ${selected.author||t('自己的图片')} · ${t('仅限非商业使用')}`;$('detailDescription').textContent=selected.description[language];$('detailDownloads').textContent=selected.private?t('图片仅在当前浏览器中预览'):'↓ '+count(selected.downloads);$('localImport').hidden=!!selected.private;$('localImportHint').hidden=!!selected.private;$('download').hidden=false;$('downloadConfig').hidden=false;$('workshop').hidden=false;$('downloadHint').hidden=false;}
async function open(item){selected=item;detailText();$('detail').showModal();if(!preview)preview=new CodexPreview($('desktopPreview'));try{await preview.setAsset(item.url,item.config);}catch(e){toast(e.message);}}
$('closeDetail').onclick=()=>$('detail').close();
$('workshop').onclick=async()=>{if(!selected)return;try{const response=await fetch(selected.url);const blob=await response.blob();const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(blob);});localStorage.setItem('bubble-studio-handoff',JSON.stringify({name:selected.filename,data,config:selected.config}));location.href='workshop.html?v=97a690010c3b';}catch(e){toast(e.message);}};
async function downloadBundle(item){if(item.private){const response=await fetch(item.url);download(await response.blob(),item.filename);download(new Blob([JSON.stringify({version:1,filename:item.filename,config:item.config},null,2)],{type:'application/json'}),item.filename.replace(/\.png$/i,'')+'.bubble.json');return;}if(localApiAvailable){const result=await api('gallery-download',{id:item.id});const data=Uint8Array.from(atob(result.data),c=>c.charCodeAt(0));download(new Blob([data],{type:'image/png'}),result.filename);download(new Blob([JSON.stringify({version:1,filename:result.filename,config:result.config},null,2)],{type:'application/json'}),result.filename.replace(/\.png$/i,'')+'.bubble.json');item.downloads=result.downloads;cards();detailText();return;}const link=document.createElement('a');link.href=item.downloadUrl||item.url;link.download=item.filename;link.target='_blank';link.rel='noopener';link.click();download(new Blob([JSON.stringify({version:1,filename:item.filename,config:item.config},null,2)],{type:'application/json'}),item.filename.replace(/\.png$/i,'')+'.bubble.json');}
$('download').onclick=async()=>{if(!selected)return;const button=$('download'),item=selected;button.disabled=true;try{await downloadBundle(item);}catch(e){toast(e.message);}finally{button.disabled=false;}};
function download(blob,filename){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('downloadConfig').onclick=()=>{if(!selected)return;download(new Blob([JSON.stringify({version:1,filename:selected.filename,config:selected.config},null,2)],{type:'application/json'}),selected.filename.replace(/\.png$/i,'')+'.bubble.json');};
$('upload').onclick=()=>location.href='workshop.html?v=97a690010c3b';
$('pngInput').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2*1024*1024)throw Error('PNG 不得超过 2 MB');const header=new Uint8Array(await file.slice(0,8).arrayBuffer());if(header.join(',')!=='137,80,78,71,13,10,26,10')throw Error('不是有效的 PNG');const url=URL.createObjectURL(file);const img=new Image();img.src=url;try{await img.decode();const w=img.naturalWidth,h=img.naturalHeight;if(w<2||h<2||w>4096||h>4096)throw Error('图片尺寸需在 2–4096 像素内');if(privateUrl)URL.revokeObjectURL(privateUrl);privateUrl=url;const data=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});localStorage.setItem('bubble-studio-handoff',JSON.stringify({name:file.name,data,config:{...{width:w,height:h,left:Math.round(w*.35),right:Math.round(w*.73),top:Math.round(h*.45),bottom:Math.round(h*.55),scale:Math.max(.01,Math.min(.6,240/w,98/h)),padding:[29,37,36,48],color:'#44362f',radius:0,borderWidth:0,borderColor:'#d0d0d0'}}}));location.href='workshop.html?v=97a690010c3b';}catch(e){if(privateUrl!==url)URL.revokeObjectURL(url);throw e;}}catch(e){toast(e.message);}finally{e.target.value='';}};
let refreshSubmission=()=>{};
$('language').onclick=()=>{setLanguage(language==='en'?'zh':'en');refreshSubmission();translatePage();document.title=t('气泡库 · DIY Codex Bubble');notice();cards();detailText();preview?.refreshLanguage();};
function notice(){$('downloadHint').textContent=t(localApiAvailable?'下载次数按成功的本机下载请求计，不是独立用户数。':'下载次数由 GitHub Releases 提供，更新可能有延迟；不是独立用户数。');}
async function downloadStats(){if(!items.length||!items[0].downloadStatsUrl)return;try{const response=await fetch(items[0].downloadStatsUrl,{headers:{Accept:'application/vnd.github+json'}});if(!response.ok)return;const release=await response.json();for(const item of items){const asset=release.assets?.find(a=>a.name===item.filename);if(asset&&Number.isInteger(asset.download_count))item.downloads=asset.download_count;}cards();detailText();}catch{}}
async function staticLibrary(){const response=await fetch('./presets/manifest.json');if(!response.ok)throw Error('素材不存在');const manifest=await response.json();items=manifest.items.map(item=>({...item,width:item.config.width,height:item.config.height,url:'./presets/'+item.filename,downloads:null}));try{const response=await fetch('./community-gallery/manifest.json');if(response.ok){const community=await response.json();items.push(...community.items.map(item=>({...item,width:item.config.width,height:item.config.height,url:'./community-gallery/'+item.filename,downloads:null})));}}catch{}localApiAvailable=false;notice();cards();downloadStats();}
translatePage();document.title=t('气泡库 · DIY Codex Bubble');
if(document.body.dataset.mode==='static')staticLibrary().catch(e=>toast(e.message));
else api('gallery').then(data=>{localApiAvailable=true;items=data.items;notice();cards();}).catch(()=>staticLibrary().catch(e=>toast(e.message)));

refreshSubmission=initSubmission();

$('localImport').onclick=()=>{if(!selected||selected.private)return;const target=new URL(localApiAvailable?location.origin:'http://127.0.0.1:19329/');target.searchParams.set('bubble',selected.id);target.searchParams.set('kind',selected.community?'community':'preset');window.open(target.href,'_blank','noopener');};
